on:
  schedule:
    - cron: "0 23 * * 0"
  

name: "Healthcheck on BQ's tables"
jobs:
  healthcheck:
    name: "Healthcheck"
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: $({ secrets.GITHUB_TOKEN })
      LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
      BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
      CRAN: "https://packagemanager.posit.co/cran/__linux__/jammy/latest"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          use-public-rspm: true
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          options(repos = c(CRAN = 'https://packagemanager.posit.co/cran/__linux__/jammy/latest'), download.file.method = 'libcurl')
          options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version["platform"], R.version["arch"], R.version["os"])))
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Healthcheck
        run: Rscript R/healthcheck/music.R